## Importing the libraries

In [101]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [102]:
dataset= pd.read_csv("Data.csv")
X=dataset.iloc[:,0:-1].values
y=dataset.iloc[:,-1].values

In [103]:
y=y.reshape(len(y),1)
print(y)

[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


## Splitting the dataset

In [104]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Feature Scaling 

In [105]:
from sklearn.preprocessing import StandardScaler
sc_X= StandardScaler()
sc_y=StandardScaler()
X_train=sc_X.fit_transform(X_train)
y_train=sc_y.fit_transform(y_train)

In [106]:
print(X_train)

[[-1.13572795 -0.88685592  0.67357894  0.52070558]
 [-0.80630243 -0.00971567  0.45145467  0.14531044]
 [ 1.77128416  1.84743445  0.24279248 -1.88374143]
 ...
 [-0.38409993 -1.24886277  0.84522042  0.13092486]
 [-0.9232821  -1.04155299  1.54693117  0.8830852 ]
 [ 1.70136528  1.05824381 -1.20438076 -2.42285818]]


In [107]:
print(y_train)

[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


## Training the model

In [108]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf')
regressor.fit(X_train,y_train)

C:\Users\Shashish Maurya\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

## Predicting the test set results

In [113]:
y_pred=sc_y.inverse_transform(regressor.predict(sc_X.transform(X_test)))
y_pred=y_pred.reshape(len(y_pred),1)
np.set_printoptions(precision=2)
print(np.concatenate((y_test,y_pred),1))

[[431.23 434.05]
 [460.01 457.94]
 [461.14 461.03]
 ...
 [473.26 470.6 ]
 [438.   439.42]
 [463.28 460.92]]


## Evaluating the model performance

In [111]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9480784049986258